stages:
  - build
  - publish

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

publish:
  stage: publish
  image: rust:latest
  script:
    - cargo login $CRATES_IO_KEY
    - cd /ntest_test_cases
    - cargo publish --verbose
    - cd /ntest
    - cargo publish --verbose
  only:
    - master
    - tags