stages:
  - build
  - publish

link-checker-mlc:
  stage: build
  image: rust:latest
  script:
    - curl https://gitlab.com/becheran/mlc/uploads/195ff024ebc575774185b79fa7adaa5d/mlc -o mlc
    - chmod +x mlc
    - ./mlc

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true

publish:
  stage: publish
  image: rust:latest
  script:
    - echo "published new version to crates.io"
  only:
    - tags
  except:
    - branches